import { StyleSheet, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0B0F17",
  },
  container: {
    flex: 1,
  },
  scrollContainer: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 36,
  },
  headerSquareBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  bellBadge: {
    position: "absolute",
    top: 4,
    right: 4,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  bellBadgeText: {
    color: "#FFFFFF",
    fontSize: 9.5,
    fontWeight: "800",
  },
  identityCard: {
    borderRadius: 22,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.25)",
    backgroundColor: "#0E1522",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  coverBannerWrap: {
    height: 110,
    width: "100%",
    position: "relative",
  },
  coverBannerImg: {
    width: "100%",
    height: "100%",
  },
  coverGradient: {
    position: "absolute",
    inset: 0,
  },
  editBtn: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  identityBody: {
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  identityLeft: {
    flex: 1,
    paddingRight: 12,
  },
  roleBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
    marginBottom: 4,
  },
  roleBadgeText: {
    color: "#D8B282",
    fontSize: 9.5,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  displayName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#FFFFFF",
    lineHeight: 23,
  },
  phoneRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 4,
  },
  phoneText: {
    fontSize: 12.5,
    fontWeight: "600",
    color: "#D8B282",
  },
  avatarWrap: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: "#D8B282",
    padding: 2,
  },
  avatarImg: {
    width: "100%",
    height: "100%",
    borderRadius: 28,
  },
  avatarCircle: {
    width: "100%",
    height: "100%",
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitialText: {
    color: "#D8B282",
    fontSize: 22,
    fontWeight: "800",
  },
  locationBanner: {
    marginTop: 12,
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.22)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  locationLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  locationDotWrap: {
    width: 10,
    height: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  locationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  locationTitleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  locationTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  locationDesc: {
    fontSize: 10.5,
    color: "#94A3B8",
    marginTop: 1,
  },
  enableLocationBtn: {
    borderRadius: 10,
    overflow: "hidden",
  },
  enableLocationBtnGrad: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  enableLocationBtnText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#050811",
  },
  sectionToday: {
    marginTop: 20,
  },
  todayHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  todaySectionTitle: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#94A3B8",
    letterSpacing: 0.8,
  },
  viewCalendarBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  viewCalendarText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#D8B282",
    marginRight: 2,
  },
  todayDateTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#FFFFFF",
    marginTop: 2,
    textTransform: "capitalize",
  },
  tabsRow: {
    flexDirection: "row",
    gap: 6,
    marginTop: 12,
    padding: 4,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.15)",
  },
  tabPill: {
    flex: 1,
    borderRadius: 10,
    overflow: "hidden",
  },
  tabGradientActive: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 7,
    paddingHorizontal: 4,
  },
  tabPillTextActive: {
    fontSize: 11,
    fontWeight: "800",
    color: "#050811",
  },
  tabPillTextInactive: {
    fontSize: 11,
    fontWeight: "600",
    color: "#94A3B8",
    textAlign: "center",
    paddingVertical: 7,
  },
  tabInactiveInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 7,
    gap: 3,
  },
  tabBadgeActive: {
    marginLeft: 3,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 8,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  tabBadgeTextActive: {
    fontSize: 9,
    fontWeight: "800",
    color: "#050811",
  },
  tabBadgeInactive: {
    marginLeft: 2,
    paddingHorizontal: 4,
    paddingVertical: 1,
    borderRadius: 8,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
  },
  tabBadgeTextInactive: {
    fontSize: 9,
    fontWeight: "700",
    color: "#D8B282",
  },
  quietBox: {
    marginTop: 14,
    padding: 24,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.15)",
    alignItems: "center",
  },
  quietIconWrap: {
    marginBottom: 10,
  },
  quietTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  quietSubtitle: {
    fontSize: 12,
    color: "#94A3B8",
    textAlign: "center",
    lineHeight: 17,
    maxWidth: 260,
    marginBottom: 16,
  },
  openVBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: "rgba(216, 178, 130, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
  },
  vMiniEmblem: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  openVBtnText: {
    fontSize: 12.5,
    fontWeight: "700",
    color: "#D8B282",
  },
  listContainer: {
    marginTop: 14,
    gap: 10,
  },
  eventCard: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.2)",
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  cardTag: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: "rgba(216, 178, 130, 0.12)",
  },
  cardTagText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#D8B282",
  },
  cardDate: {
    fontSize: 11.5,
    fontWeight: "600",
    color: "#94A3B8",
  },
  cardTitle: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#FFFFFF",
    lineHeight: 19,
    marginBottom: 6,
  },
  cardLocationRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  cardLocationText: {
    fontSize: 12,
    color: "#94A3B8",
    flex: 1,
  },
  cardFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 2,
    gap: 8,
  },
  confirmedPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "rgba(16, 185, 129, 0.15)",
  },
  confirmedPillText: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#10B981",
  },
  joinMeetingBtn: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: "rgba(216, 178, 130, 0.25)",
    borderWidth: 1,
    borderColor: "#D8B282",
  },
  joinMeetingBtnText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#D8B282",
  },
  viewAllEventsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderRadius: 14,
    backgroundColor: "rgba(255, 255, 255, 0.02)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.18)",
    marginTop: 4,
  },
  viewAllEventsText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#D8B282",
  },
  voiceSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  voiceSectionHeaderSub: {
    fontSize: 11.5,
    color: "#94A3B8",
    flex: 1,
  },
  newVoiceBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  newVoiceBtnText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#D8B282",
  },
  voiceCard: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.2)",
  },
  voiceCardTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  voiceMetaLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
  },
  voiceMicIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "rgba(239, 68, 68, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(239, 68, 68, 0.25)",
    alignItems: "center",
    justifyContent: "center",
  },
  voiceCardTitle: {
    fontSize: 13.5,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  voiceCardAuthor: {
    fontSize: 11,
    color: "#94A3B8",
    marginTop: 1,
  },
  playVoiceBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  playVoiceBtnNormal: {
    backgroundColor: "#D8B282",
  },
  playVoiceBtnActive: {
    backgroundColor: "#EF4444",
  },
  playVoiceBtnText: {
    fontSize: 11.5,
    fontWeight: "800",
    color: "#050C15",
  },
  playVoiceBtnActiveText: {
    fontSize: 11.5,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  voiceTranscriptBox: {
    marginTop: 10,
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderLeftWidth: 2,
    borderLeftColor: "#D8B282",
  },
  voiceTranscriptLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#D8B282",
  },
  voiceTranscriptText: {
    fontSize: 11.5,
    color: "#E2E8F0",
    fontStyle: "italic",
    lineHeight: 16,
    marginTop: 2,
  },
  waveformWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    marginTop: 10,
    paddingHorizontal: 4,
  },
  waveformBar: {
    width: 3,
    borderRadius: 2,
  },
  waveformText: {
    fontSize: 10.5,
    color: "#EF4444",
    fontWeight: "600",
    marginLeft: 6,
  },
  voiceCardFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.05)",
  },
  voiceLocationText: {
    fontSize: 11,
    color: "#94A3B8",
  },
  voiceCrmBadge: {
    fontSize: 9.5,
    color: "#D8B282",
    fontWeight: "600",
  },
  insightCard: {
    marginTop: 20,
    padding: 18,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.25)",
  },
  insightHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  insightSmallLabel: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#94A3B8",
    letterSpacing: 0.6,
  },
  insightHeadline: {
    fontSize: 18,
    fontWeight: "800",
    color: "#FFFFFF",
    lineHeight: 24,
    marginBottom: 6,
  },
  insightGoldNumber: {
    color: "#D8B282",
  },
  insightSubtitle: {
    fontSize: 12.5,
    color: "#94A3B8",
    lineHeight: 18,
    marginBottom: 12,
  },
  insightCta: {
    flexDirection: "row",
    alignItems: "center",
  },
  insightCtaText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#D8B282",
  },
  quickActionsGrid: {
    flexDirection: "row",
    gap: 8,
    marginTop: 16,
  },
  quickActionCard: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 4,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.2)",
  },
  quickActionIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: "rgba(216, 178, 130, 0.12)",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  quickActionLabel: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#FFFFFF",
    textAlign: "center",
  },
  opsSection: {
    marginTop: 22,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
  },
  opsHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  opsHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  opsSectionLabel: {
    fontSize: 10.5,
    fontWeight: "800",
    color: "#D8B282",
    letterSpacing: 0.8,
  },
  opsLiveBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    backgroundColor: "rgba(216, 178, 130, 0.12)",
  },
  opsLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#10B981",
  },
  opsLiveText: {
    fontSize: 9.5,
    fontWeight: "800",
    color: "#D8B282",
  },
  opsHeadline: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
    marginTop: 4,
  },
  opsSubtitle: {
    fontSize: 11.5,
    color: "#94A3B8",
    marginTop: 2,
    marginBottom: 14,
  },
  opsMetricsGrid: {
    flexDirection: "row",
    gap: 8,
  },
  opsMetricTile: {
    flex: 1,
    padding: 10,
    borderRadius: 16,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  metricTileHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  metricIconWrap: {
    width: 26,
    height: 26,
    borderRadius: 8,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
  metricValue: {
    fontSize: 18,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  metricSub: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "700",
  },
  metricBadgeGreen: {
    fontSize: 10,
    fontWeight: "700",
    color: "#10B981",
    marginTop: 2,
  },
  metricBadgeRed: {
    fontSize: 10,
    fontWeight: "700",
    color: "#EF4444",
    marginTop: 2,
  },
  metricBadgeGold: {
    fontSize: 10,
    fontWeight: "700",
    color: "#D8B282",
    marginTop: 2,
  },
  metricLabel: {
    fontSize: 9.5,
    color: "#94A3B8",
    marginTop: 4,
  },
  opsActionBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
    gap: 8,
  },
  opsBannerText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#E2E8F0",
  },
  opsBannerBtn: {
    borderRadius: 10,
    overflow: "hidden",
  },
  opsBannerBtnGrad: {
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  opsBannerBtnText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#050811",
  },
  aiSection: {
    marginTop: 22,
    padding: 18,
    borderRadius: 24,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.25)",
  },
  aiHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  aiHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  aiSectionLabel: {
    fontSize: 10.5,
    fontWeight: "800",
    color: "#D8B282",
    letterSpacing: 0.8,
  },
  aiViewAllBtn: {
    flexDirection: "row",
    alignItems: "center",
  },
  aiViewAllText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#D8B282",
    marginRight: 2,
  },
  aiHeadline: {
    fontSize: 16,
    fontWeight: "800",
    color: "#FFFFFF",
    marginTop: 4,
  },
  aiSubtitle: {
    fontSize: 11.5,
    color: "#94A3B8",
    marginTop: 2,
  },
  filterGroupTitle: {
    fontSize: 10,
    fontWeight: "700",
    color: "#D8B282",
    letterSpacing: 0.6,
    marginBottom: 6,
  },
  aiFilterChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.04)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  aiFilterChipActive: {
    backgroundColor: "rgba(216, 178, 130, 0.2)",
    borderColor: "#D8B282",
  },
  aiFilterChipText: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "600",
  },
  aiFilterChipTextActive: {
    color: "#D8B282",
    fontWeight: "700",
  },
  aiListCol: {
    marginTop: 8,
    gap: 10,
  },
  aiPartnerCard: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.025)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.18)",
  },
  aiPartnerTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  aiAvatarCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1.5,
    borderColor: "#D8B282",
    alignItems: "center",
    justifyContent: "center",
  },
  aiAvatarInitial: {
    fontSize: 18,
    fontWeight: "800",
    color: "#D8B282",
  },
  aiPartnerInfo: {
    flex: 1,
  },
  aiNameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  aiPartnerName: {
    fontSize: 14.5,
    fontWeight: "700",
    color: "#FFFFFF",
    flex: 1,
  },
  aiLocationTag: {
    flexDirection: "row",
    alignItems: "center",
  },
  aiLocationText: {
    fontSize: 10.5,
    color: "#D8B282",
  },
  aiMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
  },
  aiMetaText: {
    fontSize: 11.5,
    color: "#CBD5E1",
    flex: 1,
  },
  aiIndustryText: {
    fontSize: 11,
    color: "#94A3B8",
    flex: 1,
  },
  aiReasonBox: {
    marginTop: 8,
    padding: 8,
    borderRadius: 10,
    backgroundColor: "rgba(216, 178, 130, 0.08)",
    borderLeftWidth: 2,
    borderLeftColor: "#D8B282",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  aiSuggestionText: {
    fontSize: 11,
    color: "#F6E1C3",
    flex: 1,
  },
  aiMatchScoreText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#D8B282",
  },
  aiActionRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  aiConnectBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#D8B282",
  },
  aiConnectBtnText: {
    fontSize: 11.5,
    fontWeight: "800",
    color: "#050C15",
  },
  aiMessageBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.25)",
  },
  aiMessageBtnText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#D8B282",
  },
  floatingAiBtn: {
    position: "absolute",
    bottom: 24,
    right: 18,
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#D8B282",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.45,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 99,
  },
  floatingAiPing: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#10B981",
  },
  floatingAiCloseBadge: {
    position: "absolute",
    top: -6,
    right: -6,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 100,
    elevation: 9,
    borderWidth: 1.5,
    borderColor: "#FFFFFF",
  },
  eventCardImage: {
    width: "100%",
    height: 120,
    borderRadius: 12,
    marginBottom: 8,
  },
  todaySubSection: {
    gap: 10,
    marginBottom: 10,
  },
  todaySubSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  todaySubSectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  todaySubSectionTitle: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  todayCountBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  todayCountBadgeText: {
    fontSize: 10.5,
    fontWeight: "700",
  },
  partnerInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  partnerInfoText: {
    fontSize: 12.5,
    fontWeight: "600",
  },
  todayMeetActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  meetPrimaryActionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DFB76C",
    paddingVertical: 8,
    borderRadius: 10,
  },
  meetPrimaryActionText: {
    fontSize: 11.5,
    fontWeight: "800",
    color: "#050C15",
  },
  meetSecondaryActionBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "rgba(223, 183, 108, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(223, 183, 108, 0.35)",
  },
  meetSecondaryActionText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#DFB76C",
  },
  opportunityCard: {
    padding: 14,
    borderRadius: 18,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: "rgba(223, 183, 108, 0.25)",
  },
  oppCommunityTag: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 2.5,
    borderRadius: 8,
    backgroundColor: "rgba(223, 183, 108, 0.12)",
  },
  oppCommunityTagText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#DFB76C",
  },
  oppNewBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DFB76C",
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 6,
  },
  oppNewBadgeText: {
    fontSize: 9.5,
    fontWeight: "900",
    color: "#050C15",
    letterSpacing: 0.4,
  },
  oppOrgRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  oppOrgText: {
    fontSize: 12.5,
    fontWeight: "600",
  },
  oppMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 10,
  },
  oppDealBadge: {
    backgroundColor: "rgba(16, 185, 129, 0.15)",
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.3)",
  },
  oppDealBadgeText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#10B981",
  },
  oppCategoryText: {
    fontSize: 11.5,
    fontWeight: "600",
  },
  oppActionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "rgba(255, 255, 255, 0.06)",
  },
  oppDetailBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DFB76C",
    paddingVertical: 8,
    borderRadius: 10,
  },
  oppDetailBtnText: {
    fontSize: 11.5,
    fontWeight: "800",
    color: "#050C15",
  },
  oppCommunityLinkBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "rgba(223, 183, 108, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(223, 183, 108, 0.35)",
  },
  oppCommunityLinkText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#DFB76C",
  },
  ceoSuiteCard: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 8,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
  },
  ceoSuiteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  ceoSuiteTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  ceoSuiteTitle: {
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  ceoAiBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#D8B282",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    gap: 2,
  },
  ceoAiBadgeText: {
    fontSize: 10.5,
    fontWeight: "800",
    color: "#050C15",
  },
  ceoSuiteDesc: {
    fontSize: 12,
    lineHeight: 16,
    marginBottom: 12,
  },
  ceoSuiteGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  ceoSuiteBtn: {
    width: "48.5%",
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
  },
  ceoSuiteIconBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
  },
  ceoSuiteBtnTitle: {
    fontSize: 12.5,
    fontWeight: "700",
    marginBottom: 2,
  },
  ceoSuiteBtnSub: {
    fontSize: 10.5,
    lineHeight: 13,
  },
});
