import {
  Users2,
  HeartHandshake,
  Target,
  CalendarCheck,
  Users,
  BookOpen,
  BarChart3,
  Bot,
  Coins,
  Search,
  Clock,
  Landmark,
  EyeOff,
  UserCheck,
  Building2,
  Award,
  ShieldCheck,
  Globe2,
  Handshake,
  Lock,
  Server,
  Zap,
  Activity,
  Fingerprint,
} from "lucide-react";

// 9 Enterprise SaaS Solutions Data
export const ENTERPRISE_MODULES = [
  {
    id: "m1",
    num: "01",
    name: "Quản Lý Hội Viên & Tổ Chức",
    moduleName: "PHÂN HỆ HỘI VIÊN & TỔ CHỨC",
    tagline: "HỒ SƠ 360° • PHÂN NHÓM TỰ ĐỘNG",
    desc: "Số hóa 100% hồ sơ hội viên và doanh nghiệp thành viên, phân quyền đa cấp bậc, tự động hóa kỳ gia hạn và cấp thẻ định danh.",
    metric: "100% SỐ HÓA",
    highlight: "#A5F3FC",
    base: "#0284C7",
    shadow: "#0C4A6E",
    glow: "rgba(14, 165, 233, 0.7)",
    icon: Users2,
    features: [
      "Định danh số hội viên & ban lãnh đạo",
      "Tự động phân nhóm ngành nghề & quy mô",
      "Nhắc nhở gia hạn & cấp chứng nhận số",
    ],
  },
  {
    id: "m2",
    num: "02",
    name: "CRM & Quản Trị Mối Quan Hệ",
    moduleName: "PHÂN HỆ CRM & QUAN HỆ B2B",
    tagline: "LỊCH SỬ GIAO THƯƠNG • ĐIỂM GẮN KẾT",
    desc: "Theo dõi toàn diện lịch sử gặp gỡ, ghi chú cuộc họp, chấm điểm gắn kết đối tác và gợi ý thời điểm vàng tiếp cận thương vụ.",
    metric: "x3 HIỆU SUẤT",
    highlight: "#FED7AA",
    base: "#EA580C",
    shadow: "#7C2D12",
    glow: "rgba(234, 88, 12, 0.7)",
    icon: HeartHandshake,
    features: [
      "Nhật ký tương tác đa kênh thời gian thực",
      "Chấm điểm mức độ tin cậy và gắn kết",
      "Gợi ý thời điểm vàng tiếp cận hợp tác",
    ],
  },
  {
    id: "m3",
    num: "03",
    name: "Sàn Giao Thương & Deal Flow",
    moduleName: "PHÂN HỆ GIAO THƯƠNG & DEAL ROOM",
    tagline: "SÀN DEAL FLOW B2B • GHÉP CUNG CẦU",
    desc: "Sàn giao thương nội khối bảo mật cao, thuật toán AI khớp nhu cầu cung - cầu tự động theo chuỗi giá trị khép kín nghìn tỷ.",
    metric: "98% MATCH FIT",
    highlight: "#BAE6FD",
    base: "#0284C7",
    shadow: "#0369A1",
    glow: "rgba(2, 132, 199, 0.7)",
    icon: Target,
    features: [
      "Sàn giao thương nội khối bảo mật",
      "Thuật toán AI ghép đôi cung - cầu chuẩn xác",
      "Theo dõi tiến độ chốt deal & đẩy về CRM",
    ],
  },
  {
    id: "m4",
    num: "04",
    name: "Quản Trị Sự Kiện & Check-in NFC",
    moduleName: "PHÂN HỆ SỰ KIỆN & CHECK-IN NFC",
    tagline: "CHECK-IN 1 GIÂY • XẾP BÀN VIP",
    desc: "Quản lý sự kiện quy mô lớn, check-in NFC/QR siêu tốc dưới 1 giây, điều phối chỗ ngồi bàn VIP và đo lường ROI tương tác.",
    metric: "<1s CHECK-IN",
    highlight: "#FECDD3",
    base: "#E11D48",
    shadow: "#881337",
    glow: "rgba(225, 29, 72, 0.7)",
    icon: CalendarCheck,
    features: [
      "Check-in QR & NFC siêu tốc dưới 1s",
      "Điều phối bàn VIP & đón tiếp lễ tân số",
      "Báo cáo tương tác và chuyển đổi B2B",
    ],
  },
  {
    id: "m5",
    num: "05",
    name: "Cộng Đồng Liên Minh & CLB",
    moduleName: "PHÂN HỆ CỘNG ĐỒNG LIÊN MINH",
    tagline: "KẾT NỐI ĐA TẦNG • ĐIỀU HÀNH BẢO MẬT",
    desc: "Không gian kết nối khép kín cho hơn 300 câu lạc bộ và hiệp hội, chia sẻ cơ hội độc quyền, trao đổi bảo mật đa tầng.",
    metric: "300+ TỔ CHỨC",
    highlight: "#FEF08A",
    base: "#CA8A04",
    shadow: "#713F12",
    glow: "rgba(202, 138, 4, 0.7)",
    icon: Users,
    features: [
      "CLB chuyên ngành & địa phương đa cấp",
      "Kênh thảo luận kín bảo mật chuẩn Enterprise",
      "Phân quyền quản trị ban chấp hành",
    ],
  },
  {
    id: "m6",
    num: "06",
    name: "Tri Thức & Cố Vấn Chuyên Gia",
    moduleName: "PHÂN HỆ TRI THỨC & CỐ VẤN",
    tagline: "CẨM NĂNG THỰC CHIẾN • CASE STUDY",
    desc: "Thư viện tri thức quản trị doanh nghiệp độc quyền, ngân hàng biểu mẫu chuẩn mực và kết nối hội đồng cố vấn C-Level.",
    metric: "1.000+ TÀI LIỆU",
    highlight: "#FDE68A",
    base: "#D97706",
    shadow: "#78350F",
    glow: "rgba(217, 119, 6, 0.7)",
    icon: BookOpen,
    features: [
      "Thư viện tri thức điều hành độc quyền",
      "Khóa đào tạo chuyên sâu & hội thảo số",
      "Case study giải quyết khủng hoảng SME",
    ],
  },
  {
    id: "m7",
    num: "07",
    name: "Báo Cáo Dashboard & ROI",
    moduleName: "PHÂN HỆ DASHBOARD & PHÂN TÍCH ROI",
    tagline: "ĐO LƯỜNG THỰC CHẤT • ĐỊNH LƯỢNG GIÁ TRỊ",
    desc: "Hệ thống Dashboard thời gian thực đo lường hiệu quả kết nối, thống kê chính xác giá trị thương vụ giao dịch phát sinh.",
    metric: "REAL-TIME ROI",
    highlight: "#A7F3D0",
    base: "#059669",
    shadow: "#064E3B",
    glow: "rgba(5, 150, 105, 0.7)",
    icon: BarChart3,
    features: [
      "Dashboard thời gian thực trực quan",
      "Thống kê tổng giá trị giao dịch B2B",
      "Báo cáo phân tích dòng tiền và hội viên",
    ],
  },
  {
    id: "m8",
    num: "08",
    name: "AI Copilot & Matchmaking",
    moduleName: "PHÂN HỆ TRÍ TUỆ NHÂN TẠO COPILOT",
    tagline: "TRUY VẤN TỰ NHIÊN • GỢI Ý DEAL",
    desc: "Trợ lý AI phân tích năng lực đối tác bằng ngôn ngữ tự nhiên, gợi ý mở lời tiếp cận và tự động phát hiện cơ hội giao thương vàng.",
    metric: "<0.5s PHẢN HỒI",
    highlight: "#DDD6FE",
    base: "#7C3AED",
    shadow: "#4C1D95",
    glow: "rgba(124, 58, 237, 0.7)",
    icon: Bot,
    features: [
      "Hỏi đáp hồ sơ bằng ngôn ngữ tự nhiên",
      "Phân tích phần trăm độ tương thích đối tác",
      "Tự động soạn kịch bản mở lời tiếp cận",
    ],
  },
  {
    id: "m9",
    num: "09",
    name: "Tài Chính & Thu Chi Hiệp Hội",
    moduleName: "PHÂN HỆ TÀI CHÍNH & SỔ QUỸ MINH BẠCH",
    tagline: "THU CHI TỰ ĐỘNG • TẠM ỨNG & HOÀN ỨNG",
    desc: "Quản lý nguồn quỹ minh bạch, phân tách rành mạch tiền mặt và chuyển khoản, hỗ trợ tạm ứng hoàn ứng và tải phiếu thu chi tức thì.",
    metric: "100% MINH BẠCH",
    highlight: "#FBCFE8",
    base: "#DB2777",
    shadow: "#831843",
    glow: "rgba(219, 39, 119, 0.7)",
    icon: Coins,
    features: [
      "Quản lý phân hệ Thu - Chi tách bạch",
      "Kiểm soát tạm ứng & hoàn ứng chuẩn xác",
      "Xuất phiếu thu/chi và hóa đơn chuẩn in ấn",
    ],
  },
];

// 5 Challenges
export const HANGING_CHALLENGES = [
  {
    id: "c1",
    num: "01",
    title: "Dữ liệu phân tán, thiếu tập trung",
    desc: "Dữ liệu hội viên lưu rời rạc trên nhiều file excel, khó tra cứu đúng người khi phát sinh nhu cầu giao thương.",
    badge: "PHÂN MẢNH",
    icon: Search,
    metricName: "FRICTION_RATE",
    metricValue: "84%",
    diagnosticStatus: "CRITICAL_SILO",
  },
  {
    id: "c2",
    num: "02",
    title: "Tương tác nhạt nhòa sau sự kiện",
    desc: "Thiếu công cụ nhắc nhở và nhật ký theo dõi tương tác, khiến mối quan hệ với đối tác tiềm năng dần phai nhạt.",
    badge: "LÃNG PHÍ",
    icon: Clock,
    metricName: "CHURN_RISK",
    metricValue: "76%",
    diagnosticStatus: "ENGAGEMENT_LOSS",
  },
  {
    id: "c3",
    num: "03",
    title: "Khó nắm bắt nhu cầu mua bán B2B",
    desc: "Không kịp thời nắm bắt nhu cầu mua - bán từ hội viên khác do thiếu cơ chế ghép nối cơ hội tự động.",
    badge: "CHẬM TRỄ",
    icon: HeartHandshake,
    metricName: "MATCH_LATENCY",
    metricValue: "92%",
    diagnosticStatus: "OPPORTUNITY_MISSED",
  },
  {
    id: "c4",
    num: "04",
    title: "Hiệu quả kết nối chưa thành hợp đồng",
    desc: "Nhiều sự kiện gặp mặt giao lưu nhưng khó chuyển hóa thành hợp đồng kinh tế và doanh thu cụ thể sau sự kiện.",
    badge: "HÌNH THỨC",
    icon: Landmark,
    metricName: "CONVERSION_DROP",
    metricValue: "88%",
    diagnosticStatus: "DEAL_STAGNATION",
  },
  {
    id: "c5",
    num: "05",
    title: "Thiếu số liệu đo lường ROI mạng lưới",
    desc: "Ban điều hành không có số liệu chứng minh giá trị và lợi nhuận thực tế mà hoạt động hiệp hội mang lại cho hội viên.",
    badge: "MƠ HỒ",
    icon: EyeOff,
    metricName: "TELEMETRY_GAP",
    metricValue: "95%",
    diagnosticStatus: "ROI_BLINDSPOT",
  },
];

// 8 Orbiting Satellites for Section 4 ("Cùng nhau tạo ra giá trị lớn hơn")
export const CONSTELLATION_SATELLITES = [
  { id: "hiep-hoi", name: "Hiệp hội", icon: Users, desc: "Hợp tác sâu rộng với hơn 300+ Hiệp hội Doanh nghiệp toàn quốc", angle: 160 },
  { id: "doanh-nhan", name: "Doanh nhân", icon: UserCheck, desc: "Mạng lưới hơn 10.000+ Chủ tịch & CEO điều hành thực chiến", angle: 195 },
  { id: "doanh-nghiep", name: "Doanh nghiệp", icon: Building2, desc: "Liên kết chuỗi cung ứng khép kín, tối ưu hóa dòng tiền và doanh thu", angle: 230 },
  { id: "chuyen-gia", name: "Chuyên gia", icon: Award, desc: "Hội đồng cố vấn chiến lược tài chính, pháp lý và chuyển đổi số", angle: 265 },
  { id: "nha-dau-tu", name: "Nhà đầu tư", icon: Coins, desc: "Quỹ đầu tư mạo hiểm, quỹ thiên thần và cơ hội đầu tư B2B giá trị", angle: 20 },
  { id: "co-quan-quan-ly", name: "Cơ quan quản lý", icon: ShieldCheck, desc: "Cập nhật chính sách kinh tế và hỗ trợ pháp lý doanh nghiệp chuẩn mực", angle: 335 },
  { id: "to-chuc-quoc-te", name: "Tổ chức quốc tế", icon: Globe2, desc: "Xúc tiến thương mại song phương và xuất khẩu ra thị trường toàn cầu", angle: 300 },
  { id: "doi-tac-chien-luoc", name: "Đối tác chiến lược", icon: Handshake, desc: "Tập đoàn công nghệ, ngân hàng và đơn vị cung cấp hạ tầng tiên tiến", angle: 270 },
];

// Testimonials (3 Avatars like CEO 1983)
export const TESTIMONIALS = [
  {
    id: "t1",
    author: "Ông Trần Nam Long",
    title: "Chủ tịch Hiệp hội Doanh nghiệp Trẻ",
    role: "Chủ tịch Hiệp hội Doanh nghiệp Trẻ",
    company: "Tập Đoàn Đầu Tư & Công Nghệ Việt An",
    badge: "HANOIBA BẢO CHỨNG • 1.200 HỘI VIÊN",
    quote: "Business Connect đã giúp hiệp hội chúng tôi quản lý hơn 1.200 hội viên hoàn toàn tự động, tăng 45% tỷ lệ giao thương nội bộ ngay trong quý đầu tiên.",
    stats: "+45% Doanh số B2B nội khối",
    metric: ">120 TỶ GIAO THƯƠNG",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80",
    highlight: "Đầu tàu xúc tiến giao thương B2B",
  },
  {
    id: "t2",
    author: "Bà Nguyễn Mai Phương",
    title: "Phó Tổng Giám Đốc Tập Đoàn AIC",
    role: "Phó Tổng Giám Đốc Tập Đoàn AIC",
    company: "Tập Đoàn Công Nghiệp AIC Group (Top 500 VNR)",
    badge: "DOANH NHÂN TIÊN PHONG • C-LEVEL VERIFIED",
    quote: "Thẻ Titanium NFC kết hợp sàn giao thương AI giúp đội ngũ mở rộng đối tác chiến lược chỉ sau một lần chạm tại các hội nghị xúc tiến quốc tế.",
    stats: "300+ Đối tác kết nối mới",
    metric: "300+ HỢP ĐỒNG B2B",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&auto=format&fit=crop&q=80",
    highlight: "Mạng lưới cung ứng đa quốc gia",
  },
  {
    id: "t3",
    author: "Ông Lê Hoàng Vũ",
    title: "Sáng Lập & CEO Chuỗi Công Nghệ VTech",
    role: "Sáng Lập & CEO Chuỗi Công Nghệ VTech",
    company: "Tập Đoàn Tài Chính & Công Nghệ Số FTG",
    badge: "CHUYỂN ĐỔI SỐ XUẤT SẮC • ALLIANCE 1983",
    quote: "Tính năng AI Copilot hỗ trợ tìm kiếm nhà cung cấp chuẩn xác tới từng nhu cầu kỹ thuật. Một giải pháp không thể thiếu cho các hiệp hội thời kỳ số hóa.",
    stats: "Tiết kiệm 85% chi phí vận hành",
    metric: "85% TỐI ƯU VẬN HÀNH",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80",
    highlight: "Số hóa điều hành ban bệ toàn diện",
  },
];

// 6 Security Pillars
export const SECURITY_PILLARS = [
  {
    id: "sec1",
    title: "Mã hóa đầu cuối E2EE",
    desc: "Bảo vệ 100% tin nhắn, tài liệu, hồ sơ năng lực và giao dịch kinh doanh giữa các lãnh đạo và hiệp hội.",
    icon: Lock,
    code: "AES-256 / RSA-4096",
  },
  {
    id: "sec2",
    title: "Xác thực sinh trắc học & MFA",
    desc: "Bảo mật danh tính hội viên qua vân tay, khuôn mặt và mã xác thực 2 bước trên thiết bị cá nhân.",
    icon: Fingerprint,
    code: "FIDO2 / BIOMETRIC_AUTH",
  },
  {
    id: "sec3",
    title: "Tuân thủ ISO/IEC 27001 & SOC 2",
    desc: "Hệ thống vận hành theo quy chuẩn an toàn thông tin quốc tế khắt khe nhất, bảo đảm độ tin cậy tuyệt đối.",
    icon: ShieldCheck,
    code: "ISO_27001:2022 // TYPE_II",
  },
  {
    id: "sec4",
    title: "Phân quyền RBAC động đa cấp",
    desc: "Kiểm soát truy cập dữ liệu chặt chẽ theo chức vụ: Ban chấp hành, Ban thư ký, Hội viên VIP hay Khách mời.",
    icon: UserCheck,
    code: "DYNAMIC_RBAC // MULTI_ROLE",
  },
  {
    id: "sec5",
    title: "Kiểm toán tự động Audit Trail 24/7",
    desc: "Ghi nhật ký bất biến toàn bộ hoạt động truy cập và phê duyệt, sẵn sàng cho công tác kiểm tra định kỳ.",
    icon: Activity,
    code: "IMMUTABLE_LOGS // 99.99%",
  },
  {
    id: "sec6",
    title: "Hạ tầng đám mây phân tán Tier 3+",
    desc: "Máy chủ lưu trữ đặt tại trung tâm dữ liệu chuẩn quốc tế với sao lưu tự động và khả năng chống DDoS toàn diện.",
    icon: Server,
    code: "TIER_3+ // AUTO_FAILOVER",
  },
];

// Hero Stats
export const HERO_STATS = [
  { val: "300+", label: "Hiệp hội toàn quốc" },
  { val: "10.000+", label: "Doanh nghiệp liên kết" },
  { val: "98%", label: "Tỷ lệ giao thương thành công" },
  { val: "24/7", label: "Kết nối B2B thời gian thực" },
];
