name: vione-connect

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: runner
    image: vione-connect-backend:latest
    container_name: vione-connect-backend-local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=4000
    ports:
      - "4012:4000"
    networks:
      - vione-connect-network
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: vione-connect-frontend:latest
    container_name: vione-connect-frontend-local
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - NITRO_HOST=0.0.0.0
      - NODE_ENV=production
    ports:
      - "5010:5000"
    depends_on:
      - backend
    networks:
      - vione-connect-network

  db:
    image: postgres:15
    container_name: vione-connect-db-local
    restart: always
    environment:
      POSTGRES_USER: app1
      POSTGRES_PASSWORD: "5^S0CEpvYwC1(#YN1UoJ"
      POSTGRES_DB: vione_standalone_app
    ports:
      - "6433:5432"
    volumes:
      - postgres_standalone_data:/var/lib/postgresql/data
    networks:
      - vione-connect-network

  minio:
    image: minio/minio:latest
    container_name: vione-connect-minio-local
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9060:9000"
      - "9061:9001"
    volumes:
      - vione-standalone-minio-data-local:/data
    command: server /data --console-address ":9001"
    networks:
      - vione-connect-network

networks:
  vione-connect-network:
    driver: bridge

volumes:
  postgres_standalone_data:
  vione-standalone-minio-data-local:
