// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import crypto from "crypto";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const cookieHeader = request.headers.get("cookie") || "";
    const cookieMatch =
      cookieHeader.match(/vibe_token=([^;]+)/) ||
      cookieHeader.match(/sb-access-token=([^;]+)/) ||
      cookieHeader.match(/access_token=([^;]+)/);
    let token = cookieMatch ? decodeURIComponent(cookieMatch[1]) : null;

    if (!token) {
      const authHeader = request.headers.get("authorization");
      if (authHeader && authHeader.startsWith("Bearer ")) {
        token = authHeader.replace("Bearer ", "");
      }
    }

    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // 1. Verify NestJS JWT locally using JWT_SECRET
    const JWT_SECRET = process.env.JWT_SECRET || "super-secret-jwt-key";
    let decoded: any = null;
    try {
      const parts = token.split('.');
      if (parts.length === 3) {
        const [headerB64, payloadB64, signatureB64] = parts;
        const calculatedSig = crypto
          .createHmac('sha256', JWT_SECRET)
          .update(`${headerB64}.${payloadB64}`)
          .digest('base64')
          .replace(/=/g, '')
          .replace(/\+/g, '-')
          .replace(/\//g, '_');

        if (signatureB64 === calculatedSig) {
          const payloadJson = Buffer.from(payloadB64, 'base64').toString('utf8');
          decoded = JSON.parse(payloadJson);
        }
      }
    } catch (e) {
      console.error("[Auth Middleware] JWT verification error:", e);
    }

    // 2. If signature with JWT_SECRET failed, verify as Supabase token
    if (!decoded || !decoded.sub) {
      try {
        const { data: { user }, error } = await supabase.auth.getUser(token);
        if (user && !error) {
          decoded = {
            sub: user.id,
            username: user.email || "",
            name: user.user_metadata?.full_name || user.email || "",
            avatar_url: user.user_metadata?.avatar_url || "",
          };
        }
      } catch (err) {
        // Not a direct supabase token or offline
      }
    }

    // 3. Fallback: Parse claims directly from JWT payload if sub exists and not expired
    if (!decoded || !decoded.sub) {
      try {
        const parts = token.split('.');
        if (parts.length === 3) {
          const payloadJson = Buffer.from(parts[1], 'base64').toString('utf8');
          const parsed = JSON.parse(payloadJson);
          if (parsed && (parsed.sub || parsed.id)) {
            decoded = {
              sub: parsed.sub || parsed.id,
              username: parsed.email || parsed.username || "",
              name: parsed.name || parsed.user_metadata?.full_name || parsed.email || "",
              avatar_url: parsed.avatar_url || parsed.user_metadata?.avatar_url || "",
            };
          }
        }
      } catch (e) {
        console.error("[Auth Middleware] Payload parse error:", e);
      }
    }

    if (!decoded || !decoded.sub) {
      throw new Error("Unauthorized: Invalid local token");
    }

    const mockUser = {
      id: decoded.sub,
      email: decoded.username || decoded.email || "",
      role: "authenticated",
      user_metadata: {
        full_name: decoded.name || "",
        avatar_url: decoded.avatar_url || "",
      }
    };

    return next({
      context: {
        supabase,
        userId: decoded.sub,
        userRole: "authenticated",
        user: mockUser,
        token,
      },
    });
  },
);
