// BC-9.1 — Frozen error contract for Relationship Memory (Turn A + B1).

export const RELATIONSHIP_MEMORY_ERROR_CODES = [
  "RELATIONSHIP_MEMORY_UNAUTHENTICATED",
  "RELATIONSHIP_MEMORY_FORBIDDEN",
  "RELATIONSHIP_MEMORY_INVALID_INPUT",
  "RELATIONSHIP_MEMORY_UNKNOWN_KIND",
  "RELATIONSHIP_MEMORY_UNKNOWN_SUBJECT",
  "RELATIONSHIP_MEMORY_EXCLUDED_SOURCE",
  "RELATIONSHIP_MEMORY_TERMINAL_STATUS",
  "RELATIONSHIP_MEMORY_INVALID_TRANSITION",
  "RELATIONSHIP_MEMORY_INVALID_CURSOR",
  "RELATIONSHIP_MEMORY_INTERNAL_ERROR",
  // Turn B1
  "RELATIONSHIP_MEMORY_UNKNOWN_EXTRACTOR",
  "RELATIONSHIP_MEMORY_EXTRACTION_LIMIT",
  "RELATIONSHIP_MEMORY_ENTITY_AMBIGUOUS",
  "RELATIONSHIP_MEMORY_ENTITY_UNRESOLVED",
  "RELATIONSHIP_MEMORY_CANDIDATE_INVALID",
  "RELATIONSHIP_MEMORY_RECEIPT_CONFLICT",
  // Turn B2
  "RELATIONSHIP_MEMORY_RECEIPT_CLAIM_CONFLICT",
  "RELATIONSHIP_MEMORY_RECEIPT_STALE_CLAIM",
  "RELATIONSHIP_MEMORY_EXTRACTION_FAILED",
  "RELATIONSHIP_MEMORY_PERSISTENCE_CONFLICT",
  "RELATIONSHIP_MEMORY_EMBEDDING_PROVIDER_UNAVAILABLE",
  "RELATIONSHIP_MEMORY_EMBEDDING_PROVIDER_FORBIDDEN",
  "RELATIONSHIP_MEMORY_EMBEDDING_DIMENSION_MISMATCH",
  "RELATIONSHIP_MEMORY_EMBEDDING_FAILED",
  "RELATIONSHIP_MEMORY_RETRIEVAL_FAILED",
  "RELATIONSHIP_MEMORY_CONTEXT_UNAVAILABLE",
  // Turn B2b-i
  "RELATIONSHIP_MEMORY_SOURCE_NOT_FOUND",
  "RELATIONSHIP_MEMORY_SOURCE_FORBIDDEN",
  "RELATIONSHIP_MEMORY_SOURCE_STALE",
  "RELATIONSHIP_MEMORY_EXTRACTOR_NOT_FOUND",
  "RELATIONSHIP_MEMORY_EXTRACTOR_OUTPUT_INVALID",
  // Turn B2b-ii — persistence, merge, supersession
  "RELATIONSHIP_MEMORY_VERSION_CONFLICT",
  "RELATIONSHIP_MEMORY_INVALID_MERGE",
  "RELATIONSHIP_MEMORY_PROVENANCE_CONFLICT",
  "RELATIONSHIP_MEMORY_LINK_CONFLICT",
  "RELATIONSHIP_MEMORY_VISIBILITY_ESCALATION",
  "RELATIONSHIP_MEMORY_SENSITIVITY_DOWNGRADE",
  "RELATIONSHIP_MEMORY_SUPERSESSION_NOT_ALLOWED",
  // Turn B2c — embeddings, retrieval, graph, context
  "RELATIONSHIP_MEMORY_EMBEDDING_STALE",
  "RELATIONSHIP_MEMORY_RETRIEVAL_FORBIDDEN",
  "RELATIONSHIP_MEMORY_GRAPH_LIMIT_EXCEEDED",
] as const;

export type RelationshipMemoryErrorCode = (typeof RELATIONSHIP_MEMORY_ERROR_CODES)[number];

export class RelationshipMemoryError extends Error {
  readonly code: RelationshipMemoryErrorCode;
  readonly details?: Readonly<Record<string, unknown>>;
  constructor(
    code: RelationshipMemoryErrorCode,
    message?: string,
    details?: Record<string, unknown>,
  ) {
    super(message ?? code);
    this.name = "RelationshipMemoryError";
    this.code = code;
    this.details = details ? Object.freeze({ ...details }) : undefined;
  }
}

export function toRelationshipMemoryErrorCode(err: unknown): RelationshipMemoryErrorCode {
  if (err instanceof RelationshipMemoryError) return err.code;
  return "RELATIONSHIP_MEMORY_INTERNAL_ERROR";
}
