import { StyleSheet, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  stickyHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logoBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: "#DFB76C",
  },
  logoText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#050C15",
    letterSpacing: 0.8,
  },
  greetingText: {
    fontSize: 12,
    fontWeight: "500",
  },
  headerSquareBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  bellButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
  },
  unreadBadge: {
    position: "absolute",
    top: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
  },
  unreadBadgeText: {
    fontSize: 9.5,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  titleSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
    marginBottom: 8,
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: "800",
    letterSpacing: -0.5,
  },
  pageSubtitle: {
    fontSize: 12.5,
    marginTop: 2,
  },
  createCommunityBtn: {
    borderRadius: 16,
    overflow: "hidden",
  },
  createCommunityGrad: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  createCommunityText: {
    fontSize: 12,
    fontWeight: "900",
    color: "#050C15",
  },
  tabsWrapper: {
    marginTop: 8,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(216, 178, 130, 0.2)",
  },
  tabsScroll: {
    flexDirection: "row",
    gap: 16,
    paddingBottom: 8,
  },
  tabItem: {
    paddingBottom: 4,
    position: "relative",
  },
  tabItemActive: {},
  tabLabel: {
    fontSize: 13.5,
  },
  activeIndicator: {
    position: "absolute",
    bottom: -8,
    left: 0,
    right: 0,
    height: 2.5,
    borderRadius: 2,
    backgroundColor: "#DFB76C",
  },
  searchBarContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 13.5,
    padding: 0,
  },
  searchResultCount: {
    fontSize: 12,
    marginBottom: 8,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  emptyTitle: {
    fontSize: 15,
    fontWeight: "700",
    marginTop: 12,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 12.5,
    marginTop: 4,
    textAlign: "center",
  },
  communitiesList: {
    gap: 16,
  },
  communityCard: {
    borderRadius: 24,
    borderWidth: 1,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  cardBannerWrap: {
    height: 110,
    width: "100%",
    position: "relative",
  },
  cardBannerImg: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  cardBannerGrad: {
    position: "absolute",
    inset: 0,
  },
  cardCategoryBadge: {
    position: "absolute",
    top: 10,
    left: 12,
  },
  companyPill: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    borderWidth: 1,
    borderColor: "#DFB76C",
  },
  companyPillText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#DFB76C",
  },
  b2bPill: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    borderWidth: 1,
    borderColor: "#38BDF8",
  },
  b2bPillText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#38BDF8",
  },
  cardRoleBadge: {
    position: "absolute",
    top: 10,
    right: 12,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  cardRoleText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#DFB76C",
  },
  cardBody: {
    padding: 14,
    paddingTop: 0,
  },
  cardAvatarRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: -24,
    gap: 12,
  },
  cardAvatarImg: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: "#121824",
    backgroundColor: "#121824",
  },
  cardNameCol: {
    flex: 1,
    paddingTop: 28,
  },
  nameChevronRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardTitle: {
    fontSize: 15.5,
    fontWeight: "800",
    flex: 1,
    marginRight: 6,
  },
  cardDesc: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 4,
  },
  cardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
  },
  attendeesGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  avatarStack: {
    flexDirection: "row",
  },
  stackAvatar: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: "#121824",
  },
  membersCountText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#DFB76C",
  },
  metricBadgesGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  metricBadgeGold: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
  },
  metricBadgeGoldText: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#DFB76C",
  },
  metricBadgeSlate: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
  },
  metricBadgeSlateText: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#94A3B8",
  },
  cardActionsGrid: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 12,
    overflow: "hidden",
  },
  actionCol: {
    flex: 1,
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  actionColText: {
    fontSize: 11.5,
    fontWeight: "700",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
  },
  sectionMoreText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#DFB76C",
  },
  upcomingEventsList: {
    gap: 10,
  },
  upcomingEventCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
  },
  eventDateBox: {
    width: 60,
    height: 60,
    borderRadius: 14,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  eventMonthText: {
    fontSize: 9,
    fontWeight: "800",
    color: "#DFB76C",
  },
  eventDayText: {
    fontSize: 18,
    fontWeight: "900",
    color: "#DFB76C",
  },
  eventInfoCol: {
    flex: 1,
  },
  eventTitle: {
    fontSize: 13.5,
    fontWeight: "700",
  },
  eventMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 3,
  },
  eventMetaText: {
    fontSize: 11,
    color: "#94A3B8",
  },
  eventRegisterBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: "#DFB76C",
  },
  eventRegisteredBtn: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
  eventRegisterBtnText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#050C15",
  },
  eventRegisteredBtnText: {
    color: "#94A3B8",
  },
  opportunitiesList: {
    gap: 12,
  },
  opportunityCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    gap: 6,
  },
  oppTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  oppBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
  },
  oppBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#DFB76C",
  },
  oppDaysLeft: {
    fontSize: 11,
    color: "#94A3B8",
  },
  oppTitle: {
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 19,
  },
  oppOrgRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  oppOrgText: {
    fontSize: 12,
    color: "#94A3B8",
  },
  oppFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
  },
  oppValueLabel: {
    fontSize: 10,
    color: "#94A3B8",
  },
  oppValueText: {
    fontSize: 13.5,
    fontWeight: "800",
    color: "#DFB76C",
  },
  oppConnectBtn: {
    borderRadius: 12,
    overflow: "hidden",
  },
  oppConnectGrad: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  oppConnectText: {
    fontSize: 11.5,
    fontWeight: "800",
    color: "#050C15",
  },
  adminEntryCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 16,
  },
  adminEntryTitle: {
    fontSize: 14,
    fontWeight: "700",
  },
  adminEntrySubtitle: {
    fontSize: 11.5,
    color: "#94A3B8",
    marginTop: 2,
  },
  historyPanel: {
    marginTop: 10,
  },
  historyCard: {
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
  },
  historyRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  historyName: {
    fontSize: 13.5,
    fontWeight: "700",
  },
  historyTime: {
    fontSize: 11,
    color: "#94A3B8",
    marginTop: 2,
  },
  pendingPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
  },
  pendingPillText: {
    fontSize: 10.5,
    fontWeight: "700",
    color: "#DFB76C",
  },

  // ==========================================
  // LEVEL 2 DETAIL STYLES
  // ==========================================
  detailTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 1,
  },
  backButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  backButtonText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#DFB76C",
  },
  detailTopTitle: {
    fontSize: 14,
    fontWeight: "700",
    maxWidth: SCREEN_WIDTH * 0.5,
  },
  shareButton: {
    padding: 4,
  },
  detailBannerWrap: {
    height: 150,
    width: "100%",
    borderRadius: 20,
    overflow: "hidden",
    position: "relative",
  },
  detailBannerImg: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  detailBannerGrad: {
    position: "absolute",
    inset: 0,
  },
  detailCategoryPill: {
    position: "absolute",
    bottom: 12,
    right: 12,
  },
  detailHeaderSection: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginTop: -30,
    paddingHorizontal: 4,
    gap: 12,
  },
  detailAvatarImg: {
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: 3,
    borderColor: "#DFB76C",
    backgroundColor: "#121824",
  },
  detailInfoCol: {
    flex: 1,
    paddingTop: 34,
  },
  detailNameText: {
    fontSize: 18,
    fontWeight: "800",
    lineHeight: 23,
  },
  detailShortDesc: {
    fontSize: 12,
    lineHeight: 16,
    marginTop: 4,
  },
  badgesActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    flexWrap: "wrap",
    gap: 8,
  },
  badgesGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  roleBadgePill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 16,
    borderWidth: 1,
  },
  roleBadgeText: {
    fontSize: 11,
    fontWeight: "600",
  },
  editCommunityBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: "rgba(223, 183, 108, 0.15)",
    borderWidth: 1,
    borderColor: "#DFB76C",
  },
  editCommunityText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#DFB76C",
  },
  actionButtons3Col: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
  },
  primaryActionButton: {
    flex: 1,
    borderRadius: 16,
    overflow: "hidden",
  },
  actionBtnGrad: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
  },
  actionBtnText: {
    fontSize: 11.5,
    fontWeight: "900",
    color: "#050C15",
  },
  joinBannerCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
    backgroundColor: "rgba(216, 178, 130, 0.08)",
    marginTop: 12,
  },
  joinBannerTitle: {
    fontSize: 13.5,
    fontWeight: "800",
  },
  joinBannerSubtitle: {
    fontSize: 11,
    marginTop: 2,
  },
  joinNowBtn: {
    borderRadius: 14,
    overflow: "hidden",
  },
  joinNowGrad: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  joinNowText: {
    fontSize: 11.5,
    fontWeight: "900",
    color: "#050C15",
  },
  statsRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 14,
  },
  statTile: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: 1,
  },
  statValue: {
    fontSize: 16,
    fontWeight: "900",
    color: "#DFB76C",
  },
  statLabel: {
    fontSize: 10.5,
    color: "#94A3B8",
    marginTop: 2,
  },
  detailTabsWrapper: {
    marginTop: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(216, 178, 130, 0.2)",
  },
  detailTabsScroll: {
    flexDirection: "row",
    gap: 14,
    paddingBottom: 8,
  },
  detailTabItem: {
    paddingBottom: 4,
    position: "relative",
  },
  detailTabItemActive: {},
  detailTabLabel: {
    fontSize: 13,
  },
  detailActiveIndicator: {
    position: "absolute",
    bottom: -8,
    left: 0,
    right: 0,
    height: 2.5,
    borderRadius: 2,
    backgroundColor: "#DFB76C",
  },

  // ==========================================
  // TASKS SECTION STYLES
  // ==========================================
  tasksSection: {
    marginTop: 14,
    gap: 12,
  },
  tasksKpiBanner: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
  },
  tasksKpiHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  tasksIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(216, 178, 130, 0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  tasksBannerTitle: {
    fontSize: 13.5,
    fontWeight: "800",
  },
  tasksBannerSubtitle: {
    fontSize: 10.5,
    color: "#DFB76C",
    marginTop: 1,
  },
  tasksNewBtn: {
    borderRadius: 12,
    overflow: "hidden",
  },
  tasksNewGrad: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  tasksNewBtnText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#050C15",
  },
  tasks4KpiGrid: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
    paddingTop: 10,
    borderTopWidth: 1,
  },
  kpiTileBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 10,
  },
  kpiGoldBox: {
    backgroundColor: "rgba(223, 183, 108, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(223, 183, 108, 0.25)",
  },
  kpiBlueBox: {
    backgroundColor: "rgba(56, 189, 248, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.25)",
  },
  kpiGreenBox: {
    backgroundColor: "rgba(16, 185, 129, 0.12)",
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.25)",
  },
  kpiTileValue: {
    fontSize: 15,
    fontWeight: "900",
  },
  kpiTileLabel: {
    fontSize: 9.5,
    color: "#94A3B8",
    marginTop: 2,
  },
  taskFilterScroll: {
    flexDirection: "row",
    gap: 8,
    paddingVertical: 4,
  },
  taskFilterPill: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  taskFilterPillText: {
    fontSize: 11.5,
  },
  tasksListContainer: {
    gap: 12,
  },
  taskCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    gap: 6,
  },
  taskCardAssignedGlow: {
    shadowColor: "#DFB76C",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  taskCardTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  taskPriorityGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  priorityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
  },
  priorityUrgent: {
    backgroundColor: "rgba(239, 68, 68, 0.15)",
    borderColor: "rgba(239, 68, 68, 0.3)",
  },
  priorityUrgentText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#EF4444",
  },
  priorityHigh: {
    backgroundColor: "rgba(223, 183, 108, 0.15)",
    borderColor: "rgba(223, 183, 108, 0.3)",
  },
  priorityHighText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#DFB76C",
  },
  priorityMedium: {
    backgroundColor: "rgba(148, 163, 184, 0.15)",
    borderColor: "rgba(148, 163, 184, 0.3)",
  },
  priorityMediumText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#94A3B8",
  },
  priorityText: {},
  taskDeadlineRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  taskDeadlineText: {
    fontSize: 11,
    color: "#94A3B8",
  },
  statusAssignedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    backgroundColor: "rgba(223, 183, 108, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(223, 183, 108, 0.4)",
  },
  statusAssignedText: {
    fontSize: 9.5,
    fontWeight: "900",
    color: "#DFB76C",
  },
  statusProgressPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    backgroundColor: "rgba(56, 189, 248, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.3)",
  },
  statusProgressText: {
    fontSize: 9.5,
    fontWeight: "800",
    color: "#38BDF8",
  },
  statusCompletedPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
    backgroundColor: "rgba(16, 185, 129, 0.15)",
    borderWidth: 1,
    borderColor: "rgba(16, 185, 129, 0.3)",
  },
  statusCompletedText: {
    fontSize: 9.5,
    fontWeight: "800",
    color: "#10B981",
  },
  taskTitleText: {
    fontSize: 14.5,
    fontWeight: "800",
    lineHeight: 20,
    marginTop: 2,
  },
  taskDescText: {
    fontSize: 12,
    lineHeight: 17,
  },
  taskMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 6,
    paddingTop: 8,
    borderTopWidth: 1,
  },
  taskAssigneeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  taskCustomerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    maxWidth: 160,
  },
  taskMetaMuted: {
    fontSize: 11.5,
    color: "#94A3B8",
  },
  taskMetaBold: {
    fontSize: 11.5,
    fontWeight: "700",
  },
  acceptedAtRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  acceptedDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#10B981",
  },
  acceptedAtText: {
    fontSize: 10.5,
    color: "#10B981",
    fontWeight: "600",
  },
  taskActionBottomRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
  },
  acceptPromptText: {
    fontSize: 11,
    fontWeight: "600",
    color: "#DFB76C",
  },
  acceptTaskBtn: {
    borderRadius: 12,
    overflow: "hidden",
  },
  acceptTaskGrad: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  acceptTaskBtnText: {
    fontSize: 11,
    fontWeight: "900",
    color: "#050C15",
    letterSpacing: 0.3,
  },
  inProgressPromptText: {
    fontSize: 11,
    color: "#38BDF8",
  },
  completeTaskBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    backgroundColor: "#DFB76C",
  },
  completeTaskBtnText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#050C15",
  },
  completedStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  completedStatusText: {
    fontSize: 11.5,
    fontWeight: "700",
    color: "#10B981",
  },

  // Supervision styles
  supervisionSection: {
    marginTop: 14,
  },
  supervisionCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
  },
  supervisionTitle: {
    fontSize: 14.5,
    fontWeight: "800",
    marginBottom: 12,
  },
  supervisionMetricsRow: {
    flexDirection: "row",
    gap: 8,
  },
  supervisionMetricCol: {
    flex: 1,
    alignItems: "center",
  },
  supervisionMetricVal: {
    fontSize: 20,
    fontWeight: "900",
    color: "#FFFFFF",
  },
  supervisionMetricLbl: {
    fontSize: 10,
    color: "#94A3B8",
    marginTop: 2,
    textAlign: "center",
  },

  // Opportunities Detail Styles
  opportunitiesDetailSection: {
    marginTop: 14,
    gap: 12,
  },

  sectionHeaderSmall: {
    fontSize: 12.5,
    fontWeight: "800",
    letterSpacing: 0.5,
    color: "#DFB76C",
  },

  // News styles
  newsSection: {
    marginTop: 14,
    gap: 12,
  },
  newsCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    gap: 8,
  },
  newsAuthorRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  newsAuthorAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  newsAuthorName: {
    fontSize: 13.5,
    fontWeight: "700",
  },
  newsAuthorMeta: {
    fontSize: 11,
    color: "#94A3B8",
  },
  newsTitle: {
    fontSize: 14,
    fontWeight: "800",
  },
  newsContent: {
    fontSize: 12.5,
    lineHeight: 18,
  },
  newsImage: {
    width: "100%",
    height: 160,
    borderRadius: 12,
    resizeMode: "cover",
  },
  newsFooterRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
    paddingTop: 8,
    borderTopWidth: 1,
  },
  newsStatBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  newsStatText: {
    fontSize: 11.5,
    color: "#94A3B8",
  },

  // Events styles
  eventsSection: {
    marginTop: 14,
    gap: 10,
  },

  // Members styles
  membersSection: {
    marginTop: 14,
    gap: 10,
  },
  memberCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderRadius: 18,
    borderWidth: 1,
  },
  memberAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  memberNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  memberName: {
    fontSize: 13.5,
    fontWeight: "700",
  },
  adminRolePill: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 6,
    backgroundColor: "rgba(223, 183, 108, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(223, 183, 108, 0.4)",
  },
  adminRoleText: {
    fontSize: 9.5,
    fontWeight: "800",
    color: "#DFB76C",
  },
  memberTitle: {
    fontSize: 11.5,
    color: "#DFB76C",
    marginTop: 1,
  },
  memberCompany: {
    fontSize: 11,
    color: "#94A3B8",
  },
  contactBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(216, 178, 130, 0.15)",
    alignItems: "center",
    justifyContent: "center",
  },
});
