// BC-8.1 §5 §6 §27 §46 — Frozen notification kind registry.
// event → kind → domain → priority → channels → action kind → expiry policy.

import type {
  NotificationActionKind,
  NotificationChannel,
  NotificationKind,
  NotificationPreferenceCategory,
  NotificationPriority,
  NotificationSourceDomain,
} from "./types";

export interface NotificationKindDescriptor {
  sourceDomain: NotificationSourceDomain;
  category: NotificationPreferenceCategory;
  priority: NotificationPriority;
  /** Default channel set BEFORE preferences/quiet-hours are applied (§16). */
  defaultChannels: readonly NotificationChannel[];
  actionKind: NotificationActionKind;
  titleKey: string;
  bodyKey: string;
  actionLabelKey: string;
  /** Whether this kind may be suppressed by the actor's self-notification rule (§8). */
  suppressForActor: boolean;
  /** If true, the kind cannot be fully disabled via preferences (§46). */
  critical: boolean;
  /** May a daily/weekly digest defer this notification's OUT-OF-APP delivery? */
  digestEligible: boolean;
  /** Symbolic expiry policy — evaluated at dispatch/read time (§27). */
  expiryPolicy:
    | "on_meeting_response_terminal"
    | "on_meeting_start_or_cancel"
    | "on_follow_up_terminal"
    | "on_introduction_terminal"
    | "on_calendar_reauthorized"
    | "on_read"
    | "informational_30d"
    | "informational_90d"
    | "never";
}

const IN_APP: readonly NotificationChannel[] = ["in_app"];
const IN_APP_PUSH: readonly NotificationChannel[] = ["in_app", "push"];
const IN_APP_PUSH_EMAIL: readonly NotificationChannel[] = ["in_app", "push", "email"];

export const NOTIFICATION_KIND_REGISTRY: Readonly<
  Record<NotificationKind, NotificationKindDescriptor>
> = Object.freeze({
  // ── Connection ────────────────────────────────────────────────────────────
  connection_request_received: {
    sourceDomain: "connection",
    category: "connections",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_connection_incoming",
    titleKey: "bc.notif.kind.connection_request_received.title",
    bodyKey: "bc.notif.kind.connection_request_received.body",
    actionLabelKey: "bc.notif.kind.connection_request_received.action",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "informational_30d",
  },
  connection_request_accepted: {
    sourceDomain: "connection",
    category: "connections",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_connection_thread",
    titleKey: "bc.notif.kind.connection_request_accepted.title",
    bodyKey: "bc.notif.kind.connection_request_accepted.body",
    actionLabelKey: "bc.notif.kind.connection_request_accepted.action",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "informational_30d",
  },
  connection_request_declined: {
    sourceDomain: "connection",
    category: "connections",
    priority: "informational",
    defaultChannels: IN_APP,
    actionKind: "none",
    titleKey: "bc.notif.kind.connection_request_declined.title",
    bodyKey: "bc.notif.kind.connection_request_declined.body",
    actionLabelKey: "bc.notif.action.dismiss",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "informational_30d",
  },
  // ── Introduction ──────────────────────────────────────────────────────────
  introduction_request_received: {
    sourceDomain: "introduction",
    category: "introductions",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_introduction_request",
    titleKey: "bc.notif.kind.introduction_request_received.title",
    bodyKey: "bc.notif.kind.introduction_request_received.body",
    actionLabelKey: "bc.notif.kind.introduction_request_received.action",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_introduction_terminal",
  },
  introduction_request_accepted: {
    sourceDomain: "introduction",
    category: "introductions",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_introduction_request",
    titleKey: "bc.notif.kind.introduction_request_accepted.title",
    bodyKey: "bc.notif.kind.introduction_request_accepted.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_introduction_terminal",
  },
  introduction_request_declined: {
    sourceDomain: "introduction",
    category: "introductions",
    priority: "informational",
    defaultChannels: IN_APP,
    actionKind: "none",
    titleKey: "bc.notif.kind.introduction_request_declined.title",
    bodyKey: "bc.notif.kind.introduction_request_declined.body",
    actionLabelKey: "bc.notif.action.dismiss",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_introduction_terminal",
  },
  introduction_delivery_required: {
    sourceDomain: "introduction",
    category: "introductions",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_introduction_delivery",
    titleKey: "bc.notif.kind.introduction_delivery_required.title",
    bodyKey: "bc.notif.kind.introduction_delivery_required.body",
    actionLabelKey: "bc.notif.kind.introduction_delivery_required.action",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_introduction_terminal",
  },
  introduction_delivered: {
    sourceDomain: "introduction",
    category: "introductions",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_introduction_delivery",
    titleKey: "bc.notif.kind.introduction_delivered.title",
    bodyKey: "bc.notif.kind.introduction_delivered.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_introduction_terminal",
  },
  introduction_delivery_acknowledged: {
    sourceDomain: "introduction",
    category: "introductions",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_introduction_delivery",
    titleKey: "bc.notif.kind.introduction_delivery_acknowledged.title",
    bodyKey: "bc.notif.kind.introduction_delivery_acknowledged.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_introduction_terminal",
  },
  introduction_outcome_due: {
    sourceDomain: "introduction",
    category: "introductions",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_introduction_delivery",
    titleKey: "bc.notif.kind.introduction_outcome_due.title",
    bodyKey: "bc.notif.kind.introduction_outcome_due.body",
    actionLabelKey: "bc.notif.action.review",
    suppressForActor: false,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_introduction_terminal",
  },
  // ── Meeting ───────────────────────────────────────────────────────────────
  meeting_invitation_received: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "high",
    defaultChannels: IN_APP_PUSH_EMAIL,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.meeting_invitation_received.title",
    bodyKey: "bc.notif.kind.meeting_invitation_received.body",
    actionLabelKey: "bc.notif.action.respond",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_meeting_response_terminal",
  },
  meeting_invitation_accepted: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.meeting_invitation_accepted.title",
    bodyKey: "bc.notif.kind.meeting_invitation_accepted.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_meeting_start_or_cancel",
  },
  meeting_invitation_declined: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.meeting_invitation_declined.title",
    bodyKey: "bc.notif.kind.meeting_invitation_declined.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_meeting_start_or_cancel",
  },
  meeting_time_response_required: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_meeting_scheduling",
    titleKey: "bc.notif.kind.meeting_time_response_required.title",
    bodyKey: "bc.notif.kind.meeting_time_response_required.body",
    actionLabelKey: "bc.notif.action.respond",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_meeting_start_or_cancel",
  },
  meeting_final_time_ready: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_meeting_scheduling",
    titleKey: "bc.notif.kind.meeting_final_time_ready.title",
    bodyKey: "bc.notif.kind.meeting_final_time_ready.body",
    actionLabelKey: "bc.notif.action.finalize",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_meeting_start_or_cancel",
  },
  meeting_confirmed: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "normal",
    defaultChannels: IN_APP_PUSH_EMAIL,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.meeting_confirmed.title",
    bodyKey: "bc.notif.kind.meeting_confirmed.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: false,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_meeting_start_or_cancel",
  },
  meeting_cancelled: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "high",
    defaultChannels: IN_APP_PUSH_EMAIL,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.meeting_cancelled.title",
    bodyKey: "bc.notif.kind.meeting_cancelled.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "informational_30d",
  },
  meeting_upcoming_reminder: {
    sourceDomain: "meeting",
    category: "meetings",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.meeting_upcoming_reminder.title",
    bodyKey: "bc.notif.kind.meeting_upcoming_reminder.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: false,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_meeting_start_or_cancel",
  },
  meeting_outcome_missing: {
    sourceDomain: "meeting_outcome",
    category: "meetings",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.meeting_outcome_missing.title",
    bodyKey: "bc.notif.kind.meeting_outcome_missing.body",
    actionLabelKey: "bc.notif.action.record",
    suppressForActor: false,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_read",
  },
  // ── Follow-up ─────────────────────────────────────────────────────────────
  follow_up_created: {
    sourceDomain: "meeting_follow_up",
    category: "follow_ups",
    priority: "informational",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_follow_up",
    titleKey: "bc.notif.kind.follow_up_created.title",
    bodyKey: "bc.notif.kind.follow_up_created.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "on_follow_up_terminal",
  },
  follow_up_assigned: {
    sourceDomain: "meeting_follow_up",
    category: "follow_ups",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_meeting_follow_up",
    titleKey: "bc.notif.kind.follow_up_assigned.title",
    bodyKey: "bc.notif.kind.follow_up_assigned.body",
    actionLabelKey: "bc.notif.action.review",
    suppressForActor: true,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_follow_up_terminal",
  },
  follow_up_due_soon: {
    sourceDomain: "meeting_follow_up",
    category: "follow_ups",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_meeting_follow_up",
    titleKey: "bc.notif.kind.follow_up_due_soon.title",
    bodyKey: "bc.notif.kind.follow_up_due_soon.body",
    actionLabelKey: "bc.notif.action.review",
    suppressForActor: false,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_follow_up_terminal",
  },
  follow_up_overdue: {
    sourceDomain: "meeting_follow_up",
    category: "follow_ups",
    priority: "critical",
    defaultChannels: IN_APP_PUSH_EMAIL,
    actionKind: "open_meeting_follow_up",
    titleKey: "bc.notif.kind.follow_up_overdue.title",
    bodyKey: "bc.notif.kind.follow_up_overdue.body",
    actionLabelKey: "bc.notif.action.review",
    suppressForActor: false,
    critical: false,
    digestEligible: false,
    expiryPolicy: "on_follow_up_terminal",
  },
  follow_up_completed: {
    sourceDomain: "meeting_follow_up",
    category: "follow_ups",
    priority: "informational",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_follow_up",
    titleKey: "bc.notif.kind.follow_up_completed.title",
    bodyKey: "bc.notif.kind.follow_up_completed.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "informational_30d",
  },
  follow_up_cancelled: {
    sourceDomain: "meeting_follow_up",
    category: "follow_ups",
    priority: "informational",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_follow_up",
    titleKey: "bc.notif.kind.follow_up_cancelled.title",
    bodyKey: "bc.notif.kind.follow_up_cancelled.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "informational_30d",
  },
  // ── Collaboration ─────────────────────────────────────────────────────────
  shared_notes_published: {
    sourceDomain: "meeting_collaboration",
    category: "collaboration",
    priority: "normal",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_notes",
    titleKey: "bc.notif.kind.shared_notes_published.title",
    bodyKey: "bc.notif.kind.shared_notes_published.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "informational_30d",
  },
  agenda_updated: {
    sourceDomain: "meeting_collaboration",
    category: "collaboration",
    priority: "informational",
    defaultChannels: IN_APP,
    actionKind: "open_meeting_detail",
    titleKey: "bc.notif.kind.agenda_updated.title",
    bodyKey: "bc.notif.kind.agenda_updated.body",
    actionLabelKey: "bc.notif.action.view",
    suppressForActor: true,
    critical: false,
    digestEligible: true,
    expiryPolicy: "informational_30d",
  },
  // ── Calendar ──────────────────────────────────────────────────────────────
  calendar_account_revoked: {
    sourceDomain: "meeting_calendar",
    category: "calendar",
    priority: "critical",
    defaultChannels: IN_APP_PUSH_EMAIL,
    actionKind: "open_calendar_settings",
    titleKey: "bc.notif.kind.calendar_account_revoked.title",
    bodyKey: "bc.notif.kind.calendar_account_revoked.body",
    actionLabelKey: "bc.notif.action.fix",
    suppressForActor: false,
    critical: true,
    digestEligible: false,
    expiryPolicy: "on_calendar_reauthorized",
  },
  calendar_sync_failed_action_required: {
    sourceDomain: "meeting_calendar",
    category: "calendar",
    priority: "high",
    defaultChannels: IN_APP_PUSH,
    actionKind: "open_calendar_settings",
    titleKey: "bc.notif.kind.calendar_sync_failed_action_required.title",
    bodyKey: "bc.notif.kind.calendar_sync_failed_action_required.body",
    actionLabelKey: "bc.notif.action.fix",
    suppressForActor: false,
    critical: true,
    digestEligible: false,
    expiryPolicy: "on_calendar_reauthorized",
  },
});

// ── Event-to-kind mapping (§6). Bounded and versioned. ──────────────────────
export const NOTIFICATION_EVENT_TO_KIND: Readonly<Record<string, NotificationKind>> = Object.freeze(
  {
    // connection
    "connection.request.received": "connection_request_received",
    "connection.request.accepted": "connection_request_accepted",
    "connection.request.declined": "connection_request_declined",
    // introduction
    "introduction.request.received": "introduction_request_received",
    "introduction.request.accepted": "introduction_request_accepted",
    "introduction.request.declined": "introduction_request_declined",
    "introduction.delivery.required": "introduction_delivery_required",
    "introduction.delivery.delivered": "introduction_delivered",
    "introduction.delivery.acknowledged": "introduction_delivery_acknowledged",
    "introduction.outcome.due": "introduction_outcome_due",
    // meeting
    "meeting.invitation.received": "meeting_invitation_received",
    "meeting.invitation.accepted": "meeting_invitation_accepted",
    "meeting.invitation.declined": "meeting_invitation_declined",
    "meeting.time.response_required": "meeting_time_response_required",
    "meeting.final_time.ready": "meeting_final_time_ready",
    "meeting.confirmed": "meeting_confirmed",
    "meeting.cancelled": "meeting_cancelled",
    "meeting.upcoming.reminder": "meeting_upcoming_reminder",
    "meeting.outcome.missing": "meeting_outcome_missing",
    // follow-up
    "follow_up.created": "follow_up_created",
    "follow_up.assigned": "follow_up_assigned",
    "follow_up.due_soon": "follow_up_due_soon",
    "follow_up.overdue": "follow_up_overdue",
    "follow_up.completed": "follow_up_completed",
    "follow_up.cancelled": "follow_up_cancelled",
    // collaboration
    "collaboration.shared_notes.published": "shared_notes_published",
    "collaboration.agenda.updated": "agenda_updated",
    // calendar
    "calendar.account.revoked": "calendar_account_revoked",
    "calendar.sync.failed_action_required": "calendar_sync_failed_action_required",
  },
);

export function resolveKindForEvent(eventKind: string): NotificationKind | null {
  return NOTIFICATION_EVENT_TO_KIND[eventKind] ?? null;
}
