const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const ASSOC_ID = 'c1983000-0000-4000-8000-000000001983';

const OPPS = [
  {
    id: 'OPP-1983-001',
    poster_id: 'e3e8368d-e3f8-448a-a62d-c8baa50a692e',
    poster_name: 'Lê Thị Dung',
    poster_phone: '0988870888',
    poster_company: 'Công ty Cổ phần Đào tạo & Chuyển đổi số Vione',
    contact_name: 'Lê Thị Dung',
    contact_phone: '0988870888',
    contact_title: 'Chủ tịch HĐQT',
    company: 'Công ty Cổ phần Đào tạo & Chuyển đổi số Vione',
    title: 'Cần tìm nhà thầu cung cấp giải pháp chuyển đổi số & CRM ERP cho chuỗi 20 showroom',
    description: 'Yêu cầu đơn vị có năng lực triển khai hệ thống quản trị dữ liệu khách hàng, tích hợp Zalo Mini App và đồng bộ kho hàng theo thời gian thực.',
    type: 'partnership',
    budget_min: 500000000,
    budget_max: 1200000000,
    region: 'Toàn quốc',
    industry: 'Công nghệ & Viễn thông',
    deadline: new Date('2026-10-30T17:00:00Z'),
    status: 'open',
    views: 185,
    emoji: '💼',
    claimed_by_id: '3207de08-fffe-4d3f-91ac-71a8202727b4',
    claimed_by_name: 'Nguyễn Thanh Tuấn',
    claimed_at: new Date('2026-09-24T09:30:00Z'),
    claimed_phone: '0964699499',
    claimed_company: 'Sao Kim Branding',
  },
  {
    id: 'OPP-1983-002',
    poster_id: '456d956d-582d-468c-beba-d9e6d94894d2',
    poster_name: 'Nguyễn Thị Hồng Trang',
    poster_phone: '0983126918',
    poster_company: 'Công ty TNHH Thiết Bị In & Bao Bì Tân Á',
    contact_name: 'Nguyễn Thị Hồng Trang',
    contact_phone: '0983126918',
    contact_title: 'Tổng Giám Đốc',
    company: 'Công ty TNHH Thiết Bị In & Bao Bì Tân Á',
    title: 'Cung cấp máy móc ngành in, máy dán tem nhãn decal tự động tốc độ cao',
    description: 'Dây chuyền tự động dán nhãn bao bì chai lọ tròn, phẳng với độ chính xác tuyệt đối, năng suất 60-120 sản phẩm/phút. Hỗ trợ chuyển giao công nghệ và bảo trì 24/7.',
    type: 'supply',
    budget_min: 350000000,
    budget_max: 850000000,
    region: 'Miền Bắc',
    industry: 'Sản xuất & Công nghiệp',
    deadline: new Date('2026-11-15T17:00:00Z'),
    status: 'open',
    views: 142,
    emoji: '⚙️',
  },
  {
    id: 'OPP-1983-003',
    poster_id: '64f3ef04-f56c-4671-b76f-f98e02ae7f5b',
    poster_name: 'Nguyễn Trung Kiên',
    poster_phone: '0767313314',
    poster_company: 'Quỹ Đầu Tư & Quản Lý Tài Sản Vietnam Capital',
    contact_name: 'Nguyễn Trung Kiên',
    contact_phone: '0767313314',
    contact_title: 'Giám Đốc Quản Lý Quỹ',
    company: 'Quỹ Đầu Tư & Quản Lý Tài Sản Vietnam Capital',
    title: 'Tìm kiếm doanh nghiệp SME ngành sản xuất, F&B tăng trưởng tốt để đầu tư vốn cổ phần',
    description: 'Quy mô giải ngân từ 5 đến 20 tỷ đồng cho các doanh nghiệp có doanh thu tối thiểu 15 tỷ/năm, minh bạch sổ sách và có tiềm năng mở rộng chuỗi hoặc xuất khẩu.',
    type: 'investment',
    budget_min: 5000000000,
    budget_max: 20000000000,
    region: 'Toàn quốc',
    industry: 'Tài chính & Đầu tư',
    deadline: new Date('2026-12-31T17:00:00Z'),
    status: 'open',
    views: 268,
    emoji: '📈',
  },
  {
    id: 'OPP-1983-004',
    poster_id: 'c8deb973-1f3c-42f3-9291-a7dabaef7d72',
    poster_name: 'Đỗ Minh Thành',
    poster_phone: '0948396888',
    poster_company: 'Tập Đoàn Âm Thanh Biểu Diễn Pro Sound Việt Nam',
    contact_name: 'Đỗ Minh Thành',
    contact_phone: '0948396888',
    contact_title: 'Chủ tịch HĐQT',
    company: 'Tập Đoàn Âm Thanh Biểu Diễn Pro Sound Việt Nam',
    title: 'Tìm đại lý phân phối độc quyền hệ thống âm thanh hội trường & resort cao cấp khu vực Miền Trung',
    description: 'Chính sách chiết khấu lên đến 35%, hỗ trợ thiết kế âm học 3D, đào tạo kỹ thuật viên và cấp chứng nhận ủy quyền chính hãng từ các thương hiệu hàng đầu Châu Âu.',
    type: 'distribution',
    budget_min: 1000000000,
    budget_max: 3000000000,
    region: 'Miền Trung',
    industry: 'Thương mại & Dịch vụ',
    deadline: new Date('2026-10-25T17:00:00Z'),
    status: 'open',
    views: 119,
    emoji: '📢',
  },
  {
    id: 'OPP-1983-005',
    poster_id: 'd55bb641-9744-4807-b9e8-06f3e9213925',
    poster_name: 'Nguyễn Đình Toản',
    poster_phone: '0989310558',
    poster_company: 'Công ty Cổ phần Phát Triển Địa Ốc Thủ Đô',
    contact_name: 'Nguyễn Đình Toản',
    contact_phone: '0989310558',
    contact_title: 'Phó Tổng Giám Đốc PTDA',
    company: 'Công ty Cổ phần Phát Triển Địa Ốc Thủ Đô',
    title: 'Hợp tác liên doanh phát triển cụm 45 căn shophouse thương mại ven đô đã hoàn tất pháp lý 1/500',
    description: 'Dự án đã có sổ đỏ tổng thể, vị trí mặt đường trục chính kết nối cao tốc, cần đối tác đồng phát triển xây dựng và triển khai bán hàng tổng mức đầu tư 180 tỷ.',
    type: 'partnership',
    budget_min: 20000000000,
    budget_max: 50000000000,
    region: 'Miền Bắc',
    industry: 'Bất động sản',
    deadline: new Date('2026-11-30T17:00:00Z'),
    status: 'open',
    views: 310,
    emoji: '🏙️',
  },
  {
    id: 'OPP-1983-006',
    poster_id: '1e51e0ae-8ba0-4f21-8a92-ec13ec3f938a',
    poster_name: 'Phùng Quyết Thanh',
    poster_phone: '0987879689',
    poster_company: 'Công ty Cổ Phần Thiết Bị Chiếu Sáng Thông Minh SmartLight',
    contact_name: 'Phùng Quyết Thanh',
    contact_phone: '0987879689',
    contact_title: 'Giám Đốc Điều Hành',
    company: 'Công ty Cổ Phần Thiết Bị Chiếu Sáng Thông Minh SmartLight',
    title: 'Cung cấp thiết bị điện và giải pháp chiếu sáng LED thông minh tiết kiệm điện cho tòa nhà văn phòng',
    description: 'Sản xuất và phân phối đèn LED công nghiệp, hệ thống chiếu sáng thông minh IoT tiết kiệm 45% điện năng, chứng chỉ ISO 9001:2015, bảo hành 3 năm 1 đổi 1.',
    type: 'supply',
    budget_min: 200000000,
    budget_max: 800000000,
    region: 'Toàn quốc',
    industry: 'Thiết bị điện & Chiếu sáng',
    deadline: new Date('2026-11-20T17:00:00Z'),
    status: 'open',
    views: 94,
    emoji: '💡',
  },
  {
    id: 'OPP-1983-007',
    poster_id: 'a6ad1fea-987a-4465-bc8c-a6bbe5254e5d',
    poster_name: 'Nguyễn Thế Duẩn',
    poster_phone: '0984247726',
    poster_company: 'Công ty In Ấn & Bao Bì Cao Cấp Duẩn Phát',
    contact_name: 'Nguyễn Thế Duẩn',
    contact_phone: '0984247726',
    contact_title: 'Phó Chủ Tịch / Giám Đốc',
    company: 'Công ty In Ấn & Bao Bì Cao Cấp Duẩn Phát',
    title: 'Nhận thiết kế & in ấn bao bì hộp cứng cao cấp, tem nhãn bảo mật chống hàng giả xuất khẩu',
    description: 'Năng lực sản xuất 500.000 hộp/tháng bằng công nghệ in offset 6 màu Heidelberg của Đức, ép kim, phủ UV định hình, đạt tiêu chuẩn khắt khe vào thị trường Mỹ và Nhật.',
    type: 'supply',
    budget_min: 150000000,
    budget_max: 600000000,
    region: 'Miền Bắc',
    industry: 'In ấn & Bao bì',
    deadline: new Date('2026-11-10T17:00:00Z'),
    status: 'open',
    views: 125,
    emoji: '📦',
  },
  {
    id: 'OPP-1983-008',
    poster_id: '25d32ab2-59e9-4bc7-b992-0337ee2836d5',
    poster_name: 'Trần Ánh Phương',
    poster_phone: '0903299616',
    poster_company: 'Công ty Nhập Khẩu & Phân Phối Hàn Quốc HanViet Trade',
    contact_name: 'Trần Ánh Phương',
    contact_phone: '0903299616',
    contact_title: 'Giám Đốc Thương Mại',
    company: 'Công ty Nhập Khẩu & Phân Phối Hàn Quốc HanViet Trade',
    title: 'Tìm đối tác phân phối kênh siêu thị và chuỗi bán lẻ mỹ phẩm, thực phẩm sức khỏe Hàn Quốc chính ngạch',
    description: 'Sản phẩm đầy đủ hóa đơn VAT, công bố chất lượng của Bộ Y Tế, tem phụ chính hãng. Đang cung ứng vào hệ thống WinMart, Lotte Mart và các nhà thuốc lớn.',
    type: 'distribution',
    budget_min: 300000000,
    budget_max: 1500000000,
    region: 'Toàn quốc',
    industry: 'Bán lẻ & Tiêu dùng',
    deadline: new Date('2026-12-15T17:00:00Z'),
    status: 'open',
    views: 178,
    emoji: '🛒',
  },
  {
    id: 'OPP-1983-009',
    poster_id: 'a17591e4-0d07-4629-b1a6-05d756f79e6c',
    poster_name: 'Hoàng Văn Nam',
    poster_phone: '0988311882',
    poster_company: 'Công ty Cổ Phần Tiếp Vận Quốc Tế Nam Long Logistics',
    contact_name: 'Hoàng Văn Nam',
    contact_phone: '0988311882',
    contact_title: 'Tổng Giám Đốc',
    company: 'Công ty Cổ Phần Tiếp Vận Quốc Tế Nam Long Logistics',
    title: 'Cung cấp gói dịch vụ thông quan hải quan & vận tải đường biển - hàng không trọn gói tuyến Á - Âu',
    description: 'Hỗ trợ hội viên CEO 1983 mức cước ưu đãi đặc biệt giảm 15% booking cont FCL/LCL, hoàn tất thủ tục xuất nhập khẩu trong vòng 24 giờ tại các cụm cảng Hải Phòng, Cát Lái.',
    type: 'demand',
    budget_min: 100000000,
    budget_max: 2000000000,
    region: 'Toàn quốc',
    industry: 'Logistics & Vận tải',
    deadline: new Date('2026-10-31T17:00:00Z'),
    status: 'open',
    views: 136,
    emoji: '✈️',
  },
  {
    id: 'OPP-1983-010',
    poster_id: '5218a63c-b099-4911-9673-e2d71b9f853f',
    poster_name: 'Cao Văn Mạnh',
    poster_phone: '0982848884',
    poster_company: 'Công ty Cổ phần Truyền Thông & Giải Trí Viral Media Lab',
    contact_name: 'Cao Văn Mạnh',
    contact_phone: '0982848884',
    contact_title: 'Giám Đốc Sản Xuất',
    company: 'Công ty Cổ phần Truyền Thông & Giải Trí Viral Media Lab',
    title: 'Hợp tác sản xuất chuỗi video viral TikTok/Reels xây dựng nhân hiệu CEO và tăng doanh số chuyển đổi B2B',
    description: 'Gói cam kết KPI lượt xem đạt trên 1.000.000 view, định vị chuẩn chuyên gia cho lãnh đạo doanh nghiệp, bao gồm kịch bản, quay dựng chuyên nghiệp và book KOLs.',
    type: 'partnership',
    budget_min: 80000000,
    budget_max: 250000000,
    region: 'Hà Nội & TP.HCM',
    industry: 'Truyền thông & Giải trí',
    deadline: new Date('2026-11-05T17:00:00Z'),
    status: 'open',
    views: 204,
    emoji: '🚀',
  },
  {
    id: 'OPP-1983-011',
    poster_id: '23460ee9-ccb0-4073-b7cb-3840b8632e8c',
    poster_name: 'Hoàng Thị Ngọc Ánh',
    poster_phone: '0941272222',
    poster_company: 'Tập Đoàn Du Lịch & Viện Thẩm Mỹ Ánh Dương Group',
    contact_name: 'Hoàng Thị Ngọc Ánh',
    contact_phone: '0941272222',
    contact_title: 'Chủ tịch HĐQT',
    company: 'Tập Đoàn Du Lịch & Viện Thẩm Mỹ Ánh Dương Group',
    title: 'Cung cấp tour du lịch MICE & Team Building doanh nghiệp đẳng cấp 5 sao tại Phú Quốc - Đà Nẵng',
    description: 'Chuyên cơ trọn gói, phòng nghỉ tiêu chuẩn Vinpearl/InterContinental, thiết kế kịch bản gala dinner độc quyền gắn kết tinh thần đội ngũ cho doanh nghiệp 100 - 500 khách.',
    type: 'demand',
    budget_min: 400000000,
    budget_max: 1800000000,
    region: 'Toàn quốc',
    industry: 'Du lịch & Khách sạn',
    deadline: new Date('2026-11-25T17:00:00Z'),
    status: 'open',
    views: 167,
    emoji: '🏝️',
  },
  {
    id: 'OPP-1983-012',
    poster_id: '104e222f-32e8-44ea-8b06-49930ae789d2',
    poster_name: 'Triệu Văn Ba',
    poster_phone: '0973256686',
    poster_company: 'Công ty Cổ Phần Xây Dựng & Cơ Khí Nhôm Kính Ba Triệu',
    contact_name: 'Triệu Văn Ba',
    contact_phone: '0973256686',
    contact_title: 'Phó Chủ Tịch / TGĐ',
    company: 'Công ty Cổ Phần Xây Dựng & Cơ Khí Nhôm Kính Ba Triệu',
    title: 'Đấu thầu gói thi công kết cấu nhôm kính mặt dựng Unitized & hệ thống cửa chống cháy cao ốc văn phòng',
    description: 'Nhà máy gia công 8.000m2 trang bị robot CNC tự động, bảo đảm tiến độ thi công đạt 200m2/ngày, chứng chỉ kiểm định PCCC của Cục CS PCCC & CNCH.',
    type: 'supply',
    budget_min: 3000000000,
    budget_max: 12000000000,
    region: 'Miền Bắc',
    industry: 'Xây dựng & Hạ tầng',
    deadline: new Date('2026-12-10T17:00:00Z'),
    status: 'open',
    views: 221,
    emoji: '🏗️',
  },
  {
    id: 'OPP-1983-013',
    poster_id: '2cab6021-46f3-4f6d-a3d7-612e5fa6ab06',
    poster_name: 'Dương Thị Huệ',
    poster_phone: '0983971783',
    poster_company: 'Công ty Tổ Chức Sự Kiện & Hội Nghị Quốc Tế Huệ Dương',
    contact_name: 'Dương Thị Huệ',
    contact_phone: '0983971783',
    contact_title: 'Giám Đốc Điều Hành',
    company: 'Công ty Tổ Chức Sự Kiện & Hội Nghị Quốc Tế Huệ Dương',
    title: 'Nhận tài trợ & đồng hành tổ chức Đại Hội Thường Niên CEO 1983 quy mô 600 Doanh Nhân',
    description: 'Cơ hội trưng bày gian hàng B2B, phát biểu tại phiên tọa đàm kinh tế và tiếp cận trực tiếp 600 chủ doanh nghiệp sinh năm 1983 có sức mua và doanh thu lớn.',
    type: 'partnership',
    budget_min: 50000000,
    budget_max: 300000000,
    region: 'Hà Nội',
    industry: 'Sự kiện & Hội nghị',
    deadline: new Date('2026-10-18T17:00:00Z'),
    status: 'open',
    views: 289,
    emoji: '🤝',
  },
  {
    id: 'OPP-1983-014',
    poster_id: '3207de08-fffe-4d3f-91ac-71a8202727b4',
    poster_name: 'Nguyễn Thanh Tuấn',
    poster_phone: '0964699499',
    poster_company: 'Công ty Tư Vấn Chiến Lược Thương Hiệu Sao Kim',
    contact_name: 'Nguyễn Thanh Tuấn',
    contact_phone: '0964699499',
    contact_title: 'Phó Chủ Tịch / Chuyên Gia Thương Hiệu',
    company: 'Công ty Tư Vấn Chiến Lược Thương Hiệu Sao Kim',
    title: 'Tư vấn tái định vị thương hiệu, thiết kế hệ thống nhận diện số và chuẩn hóa tài liệu bán hàng B2B',
    description: 'Hơn 15 năm kinh nghiệm phục vụ 8.000+ khách hàng doanh nghiệp. Giúp các doanh nghiệp CEO 1983 nâng tầm giá trị thương hiệu và chuyên nghiệp hóa hồ sơ năng lực thầu.',
    type: 'demand',
    budget_min: 60000000,
    budget_max: 200000000,
    region: 'Toàn quốc',
    industry: 'Tư vấn chiến lược & Thương hiệu',
    deadline: new Date('2026-11-28T17:00:00Z'),
    status: 'open',
    views: 198,
    emoji: '✨',
  },
];

async function seed() {
  console.log(`Bắt đầu đồng bộ 14 cơ hội giao thương B2B vào cơ sở dữ liệu...`);
  for (const opp of OPPS) {
    await prisma.$queryRawUnsafe(`
      INSERT INTO public.opportunities (
        id, poster_id, title, description, type, budget_min, budget_max, region, industry, deadline,
        status, views, emoji, association_id, created_at, updated_at,
        claimed_by_id, claimed_by_name, claimed_at, claimed_phone, claimed_company,
        contact_name, contact_phone, contact_title, company
      ) VALUES (
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13, $14::uuid, now() - INTERVAL '3 days', now(),
        $15, $16, $17, $18, $19,
        $20, $21, $22, $23
      )
      ON CONFLICT (id) DO UPDATE SET
        poster_id = EXCLUDED.poster_id,
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        type = EXCLUDED.type,
        budget_min = EXCLUDED.budget_min,
        budget_max = EXCLUDED.budget_max,
        region = EXCLUDED.region,
        industry = EXCLUDED.industry,
        deadline = EXCLUDED.deadline,
        status = EXCLUDED.status,
        views = EXCLUDED.views,
        emoji = EXCLUDED.emoji,
        association_id = EXCLUDED.association_id,
        claimed_by_id = EXCLUDED.claimed_by_id,
        claimed_by_name = EXCLUDED.claimed_by_name,
        claimed_at = EXCLUDED.claimed_at,
        claimed_phone = EXCLUDED.claimed_phone,
        claimed_company = EXCLUDED.claimed_company,
        contact_name = EXCLUDED.contact_name,
        contact_phone = EXCLUDED.contact_phone,
        contact_title = EXCLUDED.contact_title,
        company = EXCLUDED.company,
        updated_at = now()
    `,
      opp.id,
      opp.poster_id,
      opp.title,
      opp.description,
      opp.type,
      opp.budget_min,
      opp.budget_max,
      opp.region,
      opp.industry,
      opp.deadline,
      opp.status,
      opp.views,
      opp.emoji,
      ASSOC_ID,
      opp.claimed_by_id || null,
      opp.claimed_by_name || null,
      opp.claimed_at || null,
      opp.claimed_phone || null,
      opp.claimed_company || null,
      opp.contact_name,
      opp.contact_phone,
      opp.contact_title,
      opp.company
    );
    console.log(`✓ Đã lưu cơ hội: [${opp.id}] ${opp.title.slice(0, 45)}...`);
  }

  // Also seed an interest for OPP-1983-001 if missing
  await prisma.$queryRawUnsafe(`
    INSERT INTO public.opportunity_interests (
      id, opportunity_id, member_id, message, contact, interest_level, created_at, association_id
    ) VALUES (
      'INT-1983-001', 'OPP-1983-001', '3207de08-fffe-4d3f-91ac-71a8202727b4',
      'Sao Kim sẵn sàng phối hợp xây dựng giải pháp UI/UX và kiến trúc số hóa cho showroom.',
      '0964699499', 'high', now() - INTERVAL '1 day', $1::uuid
    ) ON CONFLICT (id) DO NOTHING
  `, ASSOC_ID).catch(() => {});

  const total = await prisma.$queryRawUnsafe(`SELECT COUNT(*)::int as c FROM public.opportunities WHERE association_id = $1::uuid`, ASSOC_ID);
  console.log(`=> Hoàn thành! Tổng số cơ hội đang hoạt động trong CLB CEO 1983:`, total[0].c);
  await prisma.$disconnect();
}

seed().catch(console.error);
